# Generated by Django 2.1.5 on 2019-02-04 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 12, 1, 18, 162957)),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('close', 'Close'), ('cancelled', 'Cancelled')], default='inprogress', max_length=20),
        ),
    ]
